### ISSUE TITLE
Some issues when loading match data from colmap database

### ISSUE THREAD

**Issue by Tangshengku** [cvg/pixel-perfect-sfm#10]
Hi, thanks for your fantastic work. But I got some problems when loading .db file generated by colmap. Here is the problem trace:

Traceback (most recent call last):
  File "/home/tsk/anaconda3/envs/pixel/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tsk/anaconda3/envs/pixel/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tsk/workspace/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 209, in <module>
    args.database_path, args.image_dir, cache_path=args.cache_path)
  File "/home/tsk/workspace/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 108, in refine_keypoints_from_db
    pairs, matches, scores = read_matches_from_db(database_path)
  File "/home/tsk/workspace/pixel-perfect-sfm/pixsfm/util/colmap.py", line 38, in read_matches_from_db
    desc[image_id] = blob_to_array(data, np.uint32, (-1, c))
  File "/home/tsk/workspace/pixel-perfect-sfm/pixsfm/util/database.py", line 134, in blob_to_array
    return np.fromstring(blob, dtype=dtype).reshape(*shape)
ValueError: cannot reshape array of size 277536 into shape (128)

This seems to be the dimention of descriptor. However, I build the latest version of colmap and pycolmap from source. The .db file is generated from the colmap. Moreover, I noticed that the output dimention of descriptor is always 128. 

Thanks in advance for your reply!
Shengkun

**Comment by Skydes** [comment]
Thank you for reporting this issue. Can you please try out the branch [`fix-colmapdb`](https://github.com/cvg/pixel-perfect-sfm/tree/fix-colmapdb) and let us know if it works?

**Comment by Tangshengku** [comment]
I figure it out. There are some bugs during loading colmap .db file.
First, according to https://colmap.github.io/database.html, the data type of descriptor is uint8.
Second, some other bugs during making scores.
(You are replying when I am typing hah!) I will try the branch. If it doesn't work, I will make a PR.
Thanks!

**Comment by Tangshengku** [comment]
@Skydes Yes, the data type is right now, but I am afraid that there will still be some bugs for calculating scores between matches. I will make a PR later.

**Comment by Skydes** [comment]
Fixed by https://github.com/cvg/pixel-perfect-sfm/pull/13
