### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jhzgjhzg** [cvg/pixel-perfect-sfm#102]
`Obtaining file:///data0/wn/pixel-perfect-sfm
  Preparing metadata (setup.py) ... done
/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/pip/_vendor/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Installing collected packages: pixsfm
  Running setup.py develop for pixsfm
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [69 lines of output]
        running develop
        running egg_info
        writing pixsfm.egg-info/PKG-INFO
        writing dependency_links to pixsfm.egg-info/dependency_links.txt
        writing top-level names to pixsfm.egg-info/top_level.txt
        reading manifest file 'pixsfm.egg-info/SOURCES.txt'
        writing manifest file 'pixsfm.egg-info/SOURCES.txt'
        running build_ext
        -- The C compiler identification is GNU 7.5.0
        -- The CXX compiler identification is GNU 7.5.0
        -- Check for working C compiler: /usr/bin/cc
        -- Check for working C compiler: /usr/bin/cc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Check for working CXX compiler: /usr/bin/c++
        -- Check for working CXX compiler: /usr/bin/c++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        CMake Error at CMakeLists.txt:32 (find_package):
          By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has
          asked CMake to find a package configuration file provided by "COLMAP", but
          CMake did not find one.
        
          Could not find a package configuration file provided by "COLMAP" with any
          of the following names:
        
            COLMAPConfig.cmake
            colmap-config.cmake
        
          Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set
          "COLMAP_DIR" to a directory containing one of the above files.  If "COLMAP"
          provides a separate development package or SDK, be sure it has been
          installed.
        
        
        -- Configuring incomplete, errors occurred!
        See also "/data0/wn/pixel-perfect-sfm/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/data0/wn/pixel-perfect-sfm/setup.py", line 112, in <module>
            setup(
          File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
            return distutils.core.setup(**attrs)
          File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
            dist.run_commands()
          File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 38, in run
            self.install_for_development()
          File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 140, in install_for_development
            self.run_command('build_ext')
          File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
            cmd_obj.run()
          File "/data0/wn/pixel-perfect-sfm/setup.py", line 55, in run
            self.build_extension(ext)
          File "/data0/wn/pixel-perfect-sfm/setup.py", line 96, in build_extension
            subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
          File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '/data0/wn/pixel-perfect-sfm', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data0/wn/pixel-perfect-sfm/pixsfm', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DTESTS_ENABLED=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [69 lines of output]
    running develop
    running egg_info
    writing pixsfm.egg-info/PKG-INFO
    writing dependency_links to pixsfm.egg-info/dependency_links.txt
    writing top-level names to pixsfm.egg-info/top_level.txt
    reading manifest file 'pixsfm.egg-info/SOURCES.txt'
    writing manifest file 'pixsfm.egg-info/SOURCES.txt'
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:32 (find_package):
      By not providing "FindCOLMAP.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "COLMAP", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "COLMAP" with any
      of the following names:
    
        COLMAPConfig.cmake
        colmap-config.cmake
    
      Add the installation prefix of "COLMAP" to CMAKE_PREFIX_PATH or set
      "COLMAP_DIR" to a directory containing one of the above files.  If "COLMAP"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/data0/wn/pixel-perfect-sfm/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/data0/wn/pixel-perfect-sfm/setup.py", line 112, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/data0/wn/pixel-perfect-sfm/setup.py", line 55, in run
        self.build_extension(ext)
      File "/data0/wn/pixel-perfect-sfm/setup.py", line 96, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/data0/wn/pixel-perfect-sfm', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data0/wn/pixel-perfect-sfm/pixsfm', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DTESTS_ENABLED=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.`

I have already installed colmap and can run colmap - h, but the installation reported the above error and also reported the same error when installing pyceres. How should I solve it.

**Comment by Phil26AT** [comment]
Hi :) Did you install COLMAP from source and run `make install`? `COLMAPConfig.cmake` should be located in `/usr/local/share/colmap/` or similar.
