### ISSUE TITLE
glibcxx error (via conda on Arch)

### ISSUE THREAD

**Issue by KevinCain** [cvg/pixel-perfect-sfm#11]
As shown below, glibcxx 3.4.29 is required but not found on my system, presumably because conda 4.11.0 (the latest version for Arch at the time of writing) does not include this.

`strings /usr/lib/libstdc++.so.6 | grep GLIBCXX_3.4.29
`returns:
```
GLIBCXX_3.4.29
GLIBCXX_3.4.29
```

I created a new symbolic link from the conda lib path to the system lib shown above:
`ln -s /usr/lib/libstdc++.so.6 ./libstdc++.so.6`

However it seems conda cannot locate the above, as below:

Python (3.8.12) invocation follows:
```
Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pixsfm.refine_hloc import PixSfM
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/kevin/pixel-perfect-sfm/pixsfm/__init__.py", line 16, in <module>
from ._pixsfm import *  # noqa F403
ImportError: /home/kevin/anaconda3/envs/pixSfM/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/kevin/pixel-perfect-sfm/pixsfm/_pixsfm.cpython-38-x86_64-linux-gnu.so)
```

**Comment by KevinCain** [comment]
I was able to resolve the above by amending the `libstdc++.so.6` symbolic link in conda's PixSfM env path (e.g., `~/anaconda3/envs/pixSfM/lib/libstdc++.so.6`) to point to the system library path above.
