### ISSUE TITLE
Error: importing pixsfm

### ISSUE THREAD

**Issue by ronly2460** [cvg/pixel-perfect-sfm#126]
Hi, even after I could install pyceres, I still got this error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxxxx/pixel-perfect-sfm/pixsfm/__init__.py", line 17, in <module>
    from ._pixsfm import *  # noqa F403
ImportError: /xxxx/pixel-perfect-sfm/pixsfm/_pixsfm.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTVN5ceres18QuaternionManifoldE
```
Do you have any idea for this?

Thanks in advance.

**Comment by ronly2460** [comment]
This is fixed by #112 
so first install ceres-solver 2.10, then colmap 3.8 -> pyceres
