### ISSUE TITLE
Failed to find SuiteSparse - Did not find BLAS library

### ISSUE THREAD

**Issue by 2565xk** [cvg/pixel-perfect-sfm#140]
Sorry to bother everyone, but in the final step of 'pip install - e.' I encountered a problem, and I thought it was because I didn't install the SuiteSparse , but after downloading and compiling, I still encountered the same error. If anyone could provide any feedback or suggestions, I would greatly appreciate it! The code is as follows:
Obtaining file:///home/tang/3D/pixel-perfect-sfm
  Preparing metadata (setup.py) ... done
Installing collected packages: pixsfm
  Running setup.py develop for pixsfm
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [89 lines of output]
        running develop
        running egg_info
        writing pixsfm.egg-info/PKG-INFO
        writing dependency_links to pixsfm.egg-info/dependency_links.txt
        writing top-level names to pixsfm.egg-info/top_level.txt
        reading manifest file 'pixsfm.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'pixsfm.egg-info/SOURCES.txt'
        running build_ext
        CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
          Compatibility with CMake < 3.5 will be removed from a future version of
          CMake.
        
          Update the VERSION argument <min> value or use a ...<max> suffix to tell
          CMake that the project does not need compatibility with older versions.
        
        
        -- Looking for BLAS... - NOT found (Unsupported languages)
        CMake Error at /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:182 (message):
          Failed to find SuiteSparse - Did not find BLAS library (required for
          SuiteSparse).
        Call Stack (most recent call first):
          /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:295 (suitesparse_report_not_found)
          /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
          /usr/local/lib/cmake/Ceres/CeresConfig.cmake:181 (find_dependency)
          CMakeLists.txt:3 (find_package)
        
        
        -- Configuring incomplete, errors occurred!
        /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 112, in <module>
            setup(
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
            return distutils.core.setup(**attrs)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
            super().run_command(command)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py", line 109, in install_for_development
            self.run_command('build_ext')
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
            super().run_command(command)
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 55, in run
            self.build_extension(ext)
          File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 96, in build_extension
            subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
          File "/home/tang/anaconda3/envs/colmap/lib/python3.8/subprocess.py", line 364, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '/home/tang/3D/pixel-perfect-sfm', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/tang/3D/pixel-perfect-sfm/pixsfm', '-DPYTHON_EXECUTABLE=/home/tang/anaconda3/envs/colmap/bin/python', '-DTESTS_ENABLED=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [89 lines of output]
    running develop
    running egg_info
    writing pixsfm.egg-info/PKG-INFO
    writing dependency_links to pixsfm.egg-info/dependency_links.txt
    writing top-level names to pixsfm.egg-info/top_level.txt
    reading manifest file 'pixsfm.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'pixsfm.egg-info/SOURCES.txt'
    running build_ext
    CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
      Compatibility with CMake < 3.5 will be removed from a future version of
      CMake.
    
      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.
    
    
    -- Looking for BLAS... - NOT found (Unsupported languages)
    CMake Error at /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:182 (message):
      Failed to find SuiteSparse - Did not find BLAS library (required for
      SuiteSparse).
    Call Stack (most recent call first):
      /usr/local/lib/cmake/Ceres/FindSuiteSparse.cmake:295 (suitesparse_report_not_found)
      /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/cmake/data/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
      /usr/local/lib/cmake/Ceres/CeresConfig.cmake:181 (find_dependency)
      CMakeLists.txt:3 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 112, in <module>
        setup(
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
        return distutils.core.setup(**attrs)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
        super().run_command(command)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/command/develop.py", line 109, in install_for_development
        self.run_command('build_ext')
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
        super().run_command(command)
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 55, in run
        self.build_extension(ext)
      File "/home/tang/3D/pixel-perfect-sfm/setup.py", line 96, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args,
      File "/home/tang/anaconda3/envs/colmap/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/tang/3D/pixel-perfect-sfm', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/tang/3D/pixel-perfect-sfm/pixsfm', '-DPYTHON_EXECUTABLE=/home/tang/anaconda3/envs/colmap/bin/python', '-DTESTS_ENABLED=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yuxiang-wen** [comment]
收到，谢谢

**Comment by krwinC** [comment]
你好，请问你解决了吗，目前我也遇到了这个问题，不知道有没有什么方法能解决呢？
