### ISSUE TITLE
Build error from glog in PixSfM /src

### ISSUE THREAD

**Issue by KevinCain** [cvg/pixel-perfect-sfm#7]
Installation went smoothly for me until the final pixSfM package install via pip. Compilation reached 40%, then returned this error from the glog source packaged with pixSfM:

`/pixel-perfect-sfm/pixsfm/util/src/glog.cc:86:48: error: invalid conversion from ‘void (*)(const char*, int)’ to ‘void (*)(const char*, size_t)’ {aka ‘void (*)(const char*, long unsigned int)’} [-fpermissive]
86 |            []() { google::InstallFailureWriter(&PyBindLogStack); })`

The full error context is reprinted below:

```
[ 40%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o
/home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc: In lambda function:
/home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc:86:48: error: invalid conversion from ‘void (*)(const char*, int)’ to ‘void (*)(const char*, size_t)’ {aka ‘void (*)(const char*, long unsigned int)’} [-fpermissive]
86 |            []() { google::InstallFailureWriter(&PyBindLogStack); })
|                                                ^~~~~~~~~~~~~~~
|                                                |
|                                                void (*)(const char*, int)
In file included from /usr/local/include/colmap/util/logging.h:37,
from /home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc:1:
/usr/local/include/glog/logging.h:1972:12: note:   initializing argument 1of ‘void google::InstallFailureWriter(void (*)(const char*, size_t))’
1972 |     void (*writer)(const char* data, size_t size));
|     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:132: pixsfm/CMakeFiles/pixsfm.dir/util/src/glog.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:368: pixsfm/CMakeFiles/pixsfm.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/kevin/pixel-perfect-sfm/setup.py", line 112, in <module>
setup(
File "/home/kevin/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
return distutils.core.setup(**attrs)
File "/home/kevin/anaconda3/lib/python3.9/distutils/core.py", line 148, in setup
dist.run_commands()
File "/home/kevin/anaconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
self.run_command(cmd)
File "/home/kevin/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/home/kevin/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
self.install_for_development()
File "/home/kevin/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
self.run_command('build_ext')
File "/home/kevin/anaconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
self.distribution.run_command(command)
File "/home/kevin/anaconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
cmd_obj.run()
File "/home/kevin/pixel-perfect-sfm/setup.py", line 55, in run
self.build_extension(ext)
File "/home/kevin/pixel-perfect-sfm/setup.py", line 98, in build_extension
subprocess.check_call(['cmake', '--build', '.'] + build_args,
File "/home/kevin/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.
----------------------------------------
ERROR: Command errored out with exit status 1: /home/kevin/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kevin/pixel-perfect-sfm/setup.py'"'"'; __file__='"'"'/home/kevin/pixel-perfect-sfm/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by Skydes** [comment]
Did you install glog from source? The interface of `InstallFailureWriter` [has indeed been changed recently](https://github.com/google/glog/commit/0b83bb203d0e6d0b3f351d76306d41bf928e72ac#diff-59f5855888159e5e04a6bb3d6e2563e5f55fbbe29b081b8cc3fad424a4978c13L397) but this hasn't made it into any release. I would advise to install with a package manager (e.g. `libgoogle-glog-dev` on Ubuntu) or from source with tag v0.5.0

**Comment by KevinCain** [comment]
Thanks @Skydes for your fast, helpful reply.

To answer your question, I did not compile glog from scratch, but rather through the usual package (on Arch), e.g.:
`sudo pacman -Syu google-glog`

For the error I referenced, I made your proposed substitution (`size` --> `size_t`), but it looks like I'll have the patch elsewhere as other related variable conversion errors are halting my build, for example:

```
[  3%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/glog.cc.o
/home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc: In lambda function:
/home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc:86:48: error: invalid conversion from ‘void (*)(const char*, int)’ to ‘void (*)(const char*, size_t)’ {aka ‘void (*)(const char*, long unsigned int)’} [-fpermissive]
86 |            []() { google::InstallFailureWriter(&PyBindLogStack); })
|                                                ^~~~~~~~~~~~~~~
|                                                |
|                                                void (*)(const char*, int)
In file included from /usr/local/include/colmap/util/logging.h:37,
from /home/kevin/pixel-perfect-sfm/pixsfm/util/src/glog.cc:1:
/usr/local/include/glog/logging.h:1972:12: note:   initializing argument 1of ‘void google::InstallFailureWriter(void (*)(const char*, size_t))’
1972 |     void (*writer)(const char* data, size_t size));
```

**Comment by Skydes** [comment]
I suggested the following change: `int` -> `size_t`
```c++
void PyBindLogStack(const char* data, size_t size) {
```
Sorry for the confusion.

**Comment by Skydes** [comment]
@KevinCain Can you please let us know if [branch `fix-glog`](https://github.com/cvg/pixel-perfect-sfm/tree/fix-glog) solves your issue?

**Comment by KevinCain** [comment]
Yes, I can confirm that the branch resolves the glog errors I quoted above in this thread. Thanks for your prompt @Skydes, and following this closely. Thanks also to @Phil26AT for your patch on this new branch.
