### ISSUE TITLE
Running refine_sift_aachen fails

### ISSUE THREAD

**Issue by darfire** [cvg/pixel-perfect-sfm#81]
Hi,

Thanks for sharing your work, it's really interesting and useful. I am trying to adapt refine_sift_aachen to my dataset which is a colmap project with:
* images/*.jpg
* colmap.db as the db
* exhaustively matched images
* an initial point triangulation

I have installed the project in a virtual environment with python-3.8 on a CUDA machine.

I am running it as:
`$ python refine_sift_aachen.py --dataset colmap_project --outputs result`

The output is:
```

[2022/11/17 12:06:00 pixsfm INFO] Loaded dense extractor with configuration:
{'cache_format': 'chunked',
 'device': 'auto',
 'dtype': 'half',
 'fast_image_load': False,
 'l2_normalize': True,
 'load_cache_on_init': False,
 'max_edge': 1600,
 'model': {'name': 's2dnet'},
 'overwrite_cache': True,
 'patch_size': 8,
 'pyr_scales': [1.0],
 'resize': 'LANCZOS',
 'sparse': True,
 'use_cache': True}
[2022/11/17 12:06:35 pixsfm INFO] Building matching graph...
[2022/11/17 12:06:54 pixsfm INFO] Extracting dense features...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 795/795 [09:27<00:00,  1.40it/s]
[2022/11/17 12:16:24 pixsfm INFO] Loading featuremaps from H5 File.
100%[████████████████████] 795/795 [00:08, 97.7258it/s]
[2022/11/17 12:16:32 pixsfm INFO] Computing tracks...
[2022/11/17 12:16:32 pixsfm INFO] # graph nodes: 4009562
[2022/11/17 12:16:32 pixsfm INFO] # graph edges: 13344558
[2022/11/17 12:16:37 pixsfm INFO] # tracks: 744518
Traceback (most recent call last):
  File "refine_sift.py", line 87, in <module>
    main(**args)
  File "refine_sift.py", line 43, in main
    _, _, feature_manager = refiner.refine_keypoints_from_db(
  File "/data/code/doru/nerf/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 107, in refine_keypoints_from_db
    keypoints, ka_data, feature_manager = self.run_ka(
  File "/data/code/doru/nerf/pixel-perfect-sfm/pixsfm/refine_colmap.py", line 77, in run_ka
    ka_data = self.keypoint_adjuster.refine_multilevel(
  File "/data/code/doru/nerf/pixel-perfect-sfm/pixsfm/keypoint_adjustment/main.py", line 127, in refine_multilevel
    out = self.refine(keypoints_dict,
  File "/data/code/doru/nerf/pixel-perfect-sfm/pixsfm/keypoint_adjustment/main.py", line 236, in refine
    solver = ka.TopologicalReferenceKeypointOptimizer(
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizer(arg0: pixsfm._pixsfm._keypoint_adjustment.TopologicalReferenceKeypointOptimizerOptions, arg1: pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup, arg2: pixsfm._pixsfm._base.InterpolationConfig)

Invoked with: {'loss': {'name': 'cauchy', 'params': [0.25]}, 'solver': {'function_tolerance': 0.0, 'gradient_tolerance': 0.0, 'parameter_tolerance': 1e-05, 'minimizer_progress_to_stdout': False, 'max_num_iterations': 100, 'max_linear_solver_iterations': 200, 'max_num_consecutive_invalid_steps': 10, 'max_consecutive_nonmonotonic_steps': 10, 'use_inner_iterations': False, 'use_nonmonotonic_steps': False, 'update_state_every_iteration': False, 'num_threads': 1, 'callbacks': []}, 'print_summary': False, 'bound': 2.0, 'num_threads': -1}, <pixsfm._pixsfm._keypoint_adjustment.KeypointAdjustmentSetup object at 0x7f85fd2c53f0>, {'nodes': [[0.0, 0.0]], 'mode': 'BICUBIC', 'l2_normalize': True, 'ncc_normalize': False, 'use_float_simd': False}

```
Any ideas on what the incorrect parameter is? Thank you.

**Comment by Phil26AT** [comment]
Hi @darfire. Unfortunately I cannot reproduce your issue. The parameter list looks correct.

Can you try running the following minimal example:

```python3
import pixsfm

ops = {'loss': {'name': 'cauchy', 'params': [0.25]},
       'solver': {
              'function_tolerance': 0.0,
              'gradient_tolerance': 0.0,
              'parameter_tolerance': 1e-05,
              'minimizer_progress_to_stdout': False,
              'max_num_iterations': 100,
              'max_linear_solver_iterations': 200,
              'max_num_consecutive_invalid_steps': 10,
              'max_consecutive_nonmonotonic_steps': 10,
              'use_inner_iterations': False,
              'use_nonmonotonic_steps': False,
              'update_state_every_iteration': False,
              'num_threads': 1, 'callbacks': []},
       'print_summary': False, 'bound': 2.0, 'num_threads': -1
}
ka_setup = pixsfm.keypoint_adjustment.KeypointAdjustmentSetup()

interp = {'nodes': [[0.0, 0.0]], 'mode': 'BICUBIC', 'l2_normalize': True, 'ncc_normalize': False, 'use_float_simd': False}
pixsfm.keypoint_adjustment.TopologicalReferenceKeypointOptimizer(ops, ka_setup, interp)
```

Can you also tell us the commit id of pixsfm that you used?

**Comment by darfire** [comment]
Thank you for your reply. I have traced the issue at pycolmap binding incorrectly to ceres and the error went away.

**Comment by Linxius** [comment]
Hi @darfire ，I have the same problem with you. Could you please show me how you solve this?

**Comment by liyipeng137** [comment]
@darfire Hi，I encountered the same problem😿，can you tell me how you solved it? thank you very much🥰
