### ISSUE TITLE
Build error: there are no arguments to ‘H5is_library_threadsafe’ that depend on a template parameter

### ISSUE THREAD

**Issue by JzHuai0108** [cvg/pixel-perfect-sfm#89]
In building ppsfm on centos 7.9, cuda 10.2, I encountered the following error.
The hloc, pycolmap, pyceres, colmap, ceres-solver, etc. have been successfully built from source and installed.
```
(base) [huaijianzhu@swarm01 pixel-perfect-sfm]$ pip install -e .
Obtaining file:///project/huaijianzhu/code/slam_src/pixel-perfect-sfm
  Preparing metadata (setup.py) ... done
Installing collected packages: pixsfm
  Running setup.py develop for pixsfm
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [217 lines of output]
        running develop
        /home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running egg_info
        creating pixsfm.egg-info
        writing pixsfm.egg-info/PKG-INFO
        writing dependency_links to pixsfm.egg-info/dependency_links.txt
        writing top-level names to pixsfm.egg-info/top_level.txt
        writing manifest file 'pixsfm.egg-info/SOURCES.txt'
        reading manifest file 'pixsfm.egg-info/SOURCES.txt'
        adding license file 'LICENSE'
        writing manifest file 'pixsfm.egg-info/SOURCES.txt'
        running build_ext
        -- The C compiler identification is GNU 8.3.1
        -- The CXX compiler identification is GNU 8.3.1
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Found METIS: /usr/include (found suitable version "5.1.0", minimum required is "5.1.0")
        -- Looking for sgemm_
        -- Looking for sgemm_ - not found
        -- Looking for pthread.h
        -- Looking for pthread.h - found
        -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
        -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
        -- Looking for pthread_create in pthreads
        -- Looking for pthread_create in pthreads - not found
        -- Looking for pthread_create in pthread
        -- Looking for pthread_create in pthread - found
        -- Found Threads: TRUE
        -- Looking for sgemm_
        -- Looking for sgemm_ - found
        -- Found BLAS: /usr/lib64/libopenblas.so
        -- Looking for cheev_
        -- Looking for cheev_ - found
        -- Found LAPACK: /usr/lib64/libopenblas.so;-lpthread;-lm;-ldl
        -- Found OpenMP_C: -fopenmp (found suitable version "4.5", minimum required is "4.5")
        -- Found OpenMP: TRUE (found suitable version "4.5", minimum required is "4.5") found components: C
        -- Found required Ceres dependency: Eigen version 3.3.7 in /usr/share/eigen3
        -- Found required Ceres dependency: glog
        -- Found Ceres version: 2.2.0 installed in: /home/huaijianzhu/project/usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, SchurSpecializations]
        -- Found Boost: /usr/include (found version "1.53.0") found components: program_options filesystem system unit_test_framework
        -- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0")
        -- Found Eigen
        --   Includes : /usr/include/eigen3
        -- Found FreeImage
        --   Includes : /usr/include
        --   Libraries : /usr/lib64/libfreeimage.so
        -- Found Glog
        --   Includes : /usr/include
        --   Libraries : /usr/lib64/libglog.so
        CMake Warning (dev) at /software/cmake/3.23.2/share/cmake-3.23/Modules/FindOpenGL.cmake:315 (message):
          Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
          available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
          cmake_policy command to set the policy and suppress this warning.
        
          FindOpenGL found both a legacy GL library:
        
            OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
        
          and GLVND libraries for OpenGL and GLX:
        
            OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
            OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
        
          OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
          compatibility with CMake 3.10 and below the legacy GL library will be used.
        Call Stack (most recent call first):
          /home/huaijianzhu/project/usr/share/colmap/COLMAPConfig.cmake:109 (find_package)
          CMakeLists.txt:32 (find_package)
        This warning is for project developers.  Use -Wno-dev to suppress it.
        
        -- Found OpenGL: /usr/lib64/libOpenGL.so
        -- Found Glew
        --   Includes : /usr/include
        --   Libraries : /usr/lib64/libGLEW.so
        Compiling with AVX2 support.
        -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
        -- Found HDF5: /usr/lib64/libhdf5.so (found version "1.8.12")
        -- Found Boost: /usr/include (found version "1.53.0") found components: system serialization
        CMake Warning at third-party/HighFive/CMakeLists.txt:84 (message):
          Unit tests have been DISABLED.
        
        
        -- pybind11 v2.8.1
        -- Found PythonInterp: /home/huaijianzhu/project/anaconda3/bin/python (found version "3.9.13")
        -- Found PythonLibs: /home/huaijianzhu/project/anaconda3/lib/libpython3.9.so
        -- Performing Test HAS_FLTO
        -- Performing Test HAS_FLTO - Success
        -- Configuring done
        CMake Warning at third-party/pybind11/tools/pybind11Tools.cmake:165 (add_library):
          Cannot generate a safe runtime search path for target _pixsfm because files
          in some directories may conflict with libraries in implicit directories:
        
            runtime library [libgomp.so] in /software/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8 may be hidden by files in:
              /home/huaijianzhu/project/anaconda3/lib
        
          Some of these libraries may not be found correctly.
        Call Stack (most recent call first):
          cmake/CMakeHelper.cmake:136 (pybind11_add_module)
          pixsfm/CMakeLists.txt:22 (PIXSFM_ADD_PYMODULE)
        
        
        -- Generating done
        -- Build files have been written to: /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/build/temp.linux-x86_64-cpython-39
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featurepatch.cc.o
        [ 21%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/base/src/graph.cc.o
        [ 26%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/simple_logger.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremap.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremanager.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureview.cc.o
        [ 34%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/threading.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/featureset.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/features/src/references.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/keypoint_adjustment/src/keypoint_adjustment_options.cc.o
        [ 47%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/util/src/stringprintf.cc.o
        [ 52%] Building CXX object pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o
        In file included from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.cc:1:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In member function ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool)’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: error: there are no arguments to ‘H5is_library_threadsafe’ that depend on a template parameter, so a declaration of ‘H5is_library_threadsafe’ must be available [-fpermissive]
             H5is_library_threadsafe(&is_threadsafe);
             ^~~~~~~~~~~~~~~~~~~~~~~
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In instantiation of ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool) [with dtype = double]’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.cc:272:16:   required from here
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: error: ‘H5is_library_threadsafe’ was not declared in this scope
             H5is_library_threadsafe(&is_threadsafe);
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: note: suggested alternative: ‘sqlite3_threadsafe’
             H5is_library_threadsafe(&is_threadsafe);
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
             sqlite3_threadsafe
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In instantiation of ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool) [with dtype = float]’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.cc:273:16:   required from here
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: error: ‘H5is_library_threadsafe’ was not declared in this scope
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: note: suggested alternative: ‘sqlite3_threadsafe’
             H5is_library_threadsafe(&is_threadsafe);
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
             sqlite3_threadsafe
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In instantiation of ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool) [with dtype = half_float::half]’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.cc:274:16:   required from here
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: error: ‘H5is_library_threadsafe’ was not declared in this scope
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:28: note: suggested alternative: ‘sqlite3_threadsafe’
             H5is_library_threadsafe(&is_threadsafe);
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
             sqlite3_threadsafe
        In file included from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureview.h:25,
                         from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureview.cc:1:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In member function ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool)’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: error: there are no arguments to ‘H5is_library_threadsafe’ that depend on a template parameter, so a declaration of ‘H5is_library_threadsafe’ must be available [-fpermissive]
             H5is_library_threadsafe(&is_threadsafe);
             ^~~~~~~~~~~~~~~~~~~~~~~
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
        In file included from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/bundle_adjustment/src/bundle_adjustment_options.h:21,
                         from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/bundle_adjustment/src/bundle_adjustment_options.cc:1:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In member function ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool)’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: error: there are no arguments to ‘H5is_library_threadsafe’ that depend on a template parameter, so a declaration of ‘H5is_library_threadsafe’ must be available [-fpermissive]
             H5is_library_threadsafe(&is_threadsafe);
             ^~~~~~~~~~~~~~~~~~~~~~~
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
        In file included from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featuremanager.h:18,
                         from /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featuremanager.cc:7:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h: In member function ‘void pixsfm::FeatureSet<dtype>::UseParallelIO(bool)’:
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: error: there are no arguments to ‘H5is_library_threadsafe’ that depend on a template parameter, so a declaration of ‘H5is_library_threadsafe’ must be available [-fpermissive]
             H5is_library_threadsafe(&is_threadsafe);
             ^~~~~~~~~~~~~~~~~~~~~~~
        /project/huaijianzhu/code/slam_src/pixel-perfect-sfm/pixsfm/features/src/featureset.h:128:5: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
        gmake[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:188: pixsfm/CMakeFiles/pixsfm.dir/features/src/featureset.cc.o] Error 1
        gmake[2]: *** Waiting for unfinished jobs....
        gmake[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:230: pixsfm/CMakeFiles/pixsfm.dir/bundle_adjustment/src/bundle_adjustment_options.cc.o] Error 1
        gmake[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:174: pixsfm/CMakeFiles/pixsfm.dir/features/src/featureview.cc.o] Error 1
        gmake[2]: *** [pixsfm/CMakeFiles/pixsfm.dir/build.make:160: pixsfm/CMakeFiles/pixsfm.dir/features/src/featuremanager.cc.o] Error 1
        gmake[1]: *** [CMakeFiles/Makefile2:350: pixsfm/CMakeFiles/pixsfm.dir/all] Error 2
        gmake: *** [Makefile:136: all] Error 2
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/project/huaijianzhu/code/slam_src/pixel-perfect-sfm/setup.py", line 112, in <module>
            setup(
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
            self.run_command(cmd)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
            cmd_obj.run()
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
            self.run_command('build_ext')
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
            self.distribution.run_command(command)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
            cmd_obj.run()
          File "/project/huaijianzhu/code/slam_src/pixel-perfect-sfm/setup.py", line 55, in run
            self.build_extension(ext)
          File "/project/huaijianzhu/code/slam_src/pixel-perfect-sfm/setup.py", line 98, in build_extension
            subprocess.check_call(['cmake', '--build', '.'] + build_args,
          File "/home/huaijianzhu/project/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j']' returned non-zero exit status 2.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

```
FYI, the centos has hdf5 according to "hdcc -showconfig"
```
(base) [huaijianzhu@swarm02 usr]$ h5cc -showconfig
	    SUMMARY OF THE HDF5 CONFIGURATION
	    =================================

General Information:
-------------------
                   HDF5 Version: 1.10.6
                  Configured on: Wed Jun 15 15:26:16 UTC 2022
                  Configured by: root@a97d1f362628
                    Host system: x86_64-conda-linux-gnu
              Uname information: Linux a97d1f362628 4.14.248-189.473.amzn2.x86_64 #1 SMP Mon Sep 27 05:52:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /home/huaijianzhu/project/anaconda3

```
Can you please hint on how to solve this issue?

**Comment by JzHuai0108** [comment]
The reason is likely that the H5is_library_threadsafe is unavailable in HDF5 1.10.6 on centos 7, whereas it is available on ubuntu 20.04.
FYI, running the below command on centos 7 gives nothing
```
cd /usr/
find . -name "H5*" | xargs grep -E "H5is"
```
whereas it returns a line in /usr/serial/H5public.h on ubuntu 20.04.
By comparing the file /usr/H5public.h on centos 7 and /usr/serial/H5public.h on ubuntu 20.04,
it is clear that the H5is_library_threadsafe is missing for the centos 7 file.
```
/* Functions in H5.c */
H5_DLL herr_t H5open(void);
H5_DLL herr_t H5close(void);
H5_DLL herr_t H5dont_atexit(void);
H5_DLL herr_t H5garbage_collect(void);
H5_DLL herr_t H5set_free_list_limits (int reg_global_lim, int reg_list_lim,
                int arr_global_lim, int arr_list_lim, int blk_global_lim,
                int blk_list_lim);
H5_DLL herr_t H5get_libversion(unsigned *majnum, unsigned *minnum,
				unsigned *relnum);
H5_DLL herr_t H5check_version(unsigned majnum, unsigned minnum,
			       unsigned relnum);

```
So do I need to build hdf5 from source as for other dependencies (suitesparse, freeimage)?

**Comment by Phil26AT** [comment]
Yes I guess you would need to build hdf5 from source on centos7. This is anyway an experimental feature, and disabled by default. So you could also just outcomment the failing line in the code.

**Comment by JzHuai0108** [comment]
As you said, I comment out the H5is_library_threadsafe line (it only appears once in the whole project, and I set threadsafe true anyway because I am on a HPC), now ppsfm can be installed successfully.
